server:
  servlet:
    context-path: /api/v0.0.1/chat
spring:
  application:
    name: chat-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_SERVER}
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.dating.chat.data
    producer:
      acks: -1
      bootstrap-servers: ${KAFKA_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC+3
jwt:
  secret: ${JWT_KEY}
logging:
  level:
    root: INFO
    com.dating.chat: ERROR
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG