server:
  servlet:
    context-path: /api/v0.0.1/chat
spring:
  application:
    name: chat-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.time_zone: UTC+3
jwt:
  secret: ${JWT_KEY}
logging:
  level:
    root: INFO
    com.dating.chat: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG